# =====================================================================================================================
# Run this docker compose when you are working in development mode
# and just want to bring up Redis.
# =====================================================================================================================

name: bot-template-dev

services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
