telegram.bot.bot-name=Default
telegram.bot.buttons-per-row=1
telegram.bot.executor-core-pool-size=5
telegram.bot.executor-max-pool-size=15
telegram.bot.executor-queue-capacity=20
telegram.bot.executor-thread-name-prefix=DefBotAsync-