rootProject.name = 'telegram-dialog-bot-engine'

// Modules
include 'telegram-dialog-bot-spring-boot-starter'
project(':telegram-dialog-bot-spring-boot-starter').projectDir = file('modules/bot-engine')

include 'telegram-dialog-bot-template'
project(':telegram-dialog-bot-template').projectDir = file('modules/bot-template')
