rootProject.name = 'telegram-dialog-bots-engine'

// Modules

include 'telegram-dialog-bots-engine-spring-boot-starter'
project(':telegram-dialog-bots-engine-spring-boot-starter').projectDir = file('modules/bots-engine')

include 'telegram-dialog-bots-engine-bot-template'
project(':telegram-dialog-bots-engine-bot-template').projectDir = file('modules/bot-template')
