spring.config.import=optional:application-secret.properties

telegram.bot.bot-name=TemplateBot

##!!!Specify your bot token and uncomment this line
#telegram.bot.token=

telegram.bot.dialog-file-name=dialog.yml
telegram.bot.buttons-per-row=1
telegram.bot.executor-core-pool-size=5
telegram.bot.executor-max-pool-size=15
telegram.bot.executor-queue-capacity=20
telegram.bot.executor-thread-name-prefix=MyBotAsync-

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380