telegram.bot.name=DefaultBot
telegram.bot.dialog.buttons-per-row=1
telegram.bot.rate-limit.global.capacity=25
telegram.bot.rate-limit.global.rate=25
telegram.bot.rate-limit.global.interval=1s
telegram.bot.rate-limit.chat.capacity=3
telegram.bot.rate-limit.chat.rate=3
telegram.bot.rate-limit.chat.interval=1s
telegram.bot.broadcast.enabled=false