spring.config.import=optional:application-secret.properties

#!!! Specify your bot token and uncomment this !!!
telegram.bot.token=

# Specify the name of the bot dialog file
telegram.bot.dialog-file-name=dialog.yml

# Enter the name of your bot for logging
telegram.bot.name=TemplateBot

# Default starter settings.
# To customize, uncomment and fill in the appropriate parameters.
#telegram.bot.buttons-per-row=1
#telegram.bot.executor-core-pool-size=5
#telegram.bot.executor-max-pool-size=15
#telegram.bot.executor-queue-capacity=20
#telegram.bot.executor-thread-name-prefix=MyBotAsync-

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380