# Specify your bot token
telegram.bot.token=

# Or create a file with a secret and add the token there
spring.config.import=optional:application-secret.properties

# Enter the name of your bot for logging
telegram.bot.name=BotTemplate

# Specify the name of the bot dialog file
telegram.bot.dialog.file-name=dialog.yml

# Number of buttons in a row. Default 1.
telegram.bot.dialog.buttons-per-row=1

# Rate limit settings. The default settings are listed here.
telegram.bot.rate-limit.global.capacity=25
telegram.bot.rate-limit.global.rate=25
telegram.bot.rate-limit.global.interval=1s
telegram.bot.rate-limit.chat.capacity=3
telegram.bot.rate-limit.chat.rate=3
telegram.bot.rate-limit.chat.interval=1s

# Broadcast mailing.
# To enable this option you must:
# 1. Change the parameter to true.
# 2. Specify your broadcast file.
# 3. Specify your timezone
# 4. Redis configuration block in this file should be uncommented.
#    The file contains the default settings. You can customize them with your own values.
# 5. Run a Redis container.
#    Redis dependency is pre-configured in this template (minimally pre-set).
#    - For development: use docker-compose.redis-dev.yml
#    - For deployment: uncomment Redis blocks in docker-compose.bot-template.yml
telegram.bot.broadcast.enabled=true
telegram.bot.broadcast.file-name=broadcast.yml
telegram.bot.broadcast.timezone=Europe/Kyiv

## Redis configuration (development)
spring.data.redis.host=localhost
spring.data.redis.port=6380

# Redis configuration (deployment)
#spring.data.redis.host=redis
#spring.data.redis.port=6379