spring.config.import=optional:application-secret.properties

#!!! Specify your bot token !!!
telegram.bot.token=

# Specify the name of the bot dialog file
telegram.bot.dialog-file-name=dialog.yml

# Enter the name of your bot for logging
telegram.bot.name=BotTemplate

# Default starter settings.
# To customize, uncomment and fill in the appropriate parameters
telegram.bot.buttons-per-row=1


# Optionally, enable the /last command to preserve the user's state between interactions.
# To enable this option you must:
# 1. Change the parameter to true.
# 2. Uncomment the Redis configuration block in this file.
# 3. Run a Redis container.
# In this template, the Redis dependency is already added.
# If you use tbcf-starter separately in your projects,
# you need to add the Redis dependency manually to your dependencies.
# A Docker Compose template for the Redis container is available
# in the root directory of the shared project (docker-compose-dev.yml).
telegram.bot.enable-last-command=true

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380